---
title: "Lab 2: What Makes a Product Successful? Fall 2021"
author: 'w203: Statistics for Data Science'
date: "November 1, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 

For Lab 2, you are part of a team of product data scientists at Acme, Inc. Your manager, Mx. Coy Ote, has given you the freedom to choose your own product to investigate, and evaluate a way to make it more successful.

**Your task is to select and develop a research question, find appropriate data, then conduct a regression study.** 

### Research Question

Your research question must be specific, it should clearly state an $X$ and a $Y$, defined at a conceptual level.  Your $X$ should be a design property or characteristic of a product that could be modified in the manufacturing process, and your $Y$ should be a metric of success.

In selecting your research question, you will have to use the skills you developed in RDADA to work on a question that can be addressed using a modeling approach from this course. It is not appropriate to ask "What product features increase success?" or "How does product design affect sales?". These types of questions are not amenable to a modeling based approach and your study would likely become a fishing expedition. Instead, you and the team will have to use your background knowledge to identify a relationship you want to measure between a specific design feature and a specific metric of success.

If your data set is large enough, you can begin your process by splitting the data into an exploration set and a testing set.  As a rough guideline, you might put 30\% of your data into the exploration set, but make sure that both sets have a minimum of 200 rows of data.  Use the exploration set to build your intuition, explore the data and how it is distributed, and identify your $X$ and $Y$ variables.  Then use the testing set to fit your models.

Because your manager is interested in *changes* to a product, they are fundamentally asking you to perform an explanatory study.  As we have noted in the class, given observational data, an OLS regression is usually not a credible way to measure a causal effect.  We have purposefully selected a domain in which the one-equation structural model is at least partially defensible.  The most prominent causal pathways will go in one direction, from product design characteristics to success.  While not a perfect reflection of reality, we expect your model to be plausible enough to make your results interesting.  At the same time, you will need to analyze potential violations of the one-equation structural model and what effect any violations may have on your results.

### Data

For this lab, you and your team will be responsible for gathering the data that you use. The data should be publicly available, and should be useful in helping to answer your research question. To increase the diversity of products investigated, we are asking students to avoid working on data that is sourced from Yelp and Airbnb. There are very, very good data resources available, for example: 

New York Times
Tidy Tuesday 
ICPSR for social and political data 
Data.world
Dataverse
UC Irvine Machine Learning Data Repository
Google Dataset Search
Amazon Open Data Registry
Azure Open Data Registry  

**Requirements for your data:**

- Data should be cross-sectional (i.e. not have multiple measurements for a single unit of observation).  You may, for example, take a single cross section from a larger panel.
- We recommend a minimum of 100 or 200 observations. A team could choose to use an interesting dataset that is smaller than this, however, this will then require the team to assess and satisfy the more stringent CLM assumptions. 
- The outcome (or outcomes) that you use should be plausibly metric (i.e. number of sales of a product; number of views of a video). However, for this lab to make it easier to find product data teams may use ordinal outcome data if necessary. If using ordinal outcome data such as a 1-7 Likert scale the team should clearly discuss the consequences of failing to satisfy the assumptions of the OLS regression model.
- Your data should have sufficient inputs to your model that you can produce a convincing discussion of what is (and is not) effective for generating product satisfaction.
- Your models must include a mixture of numeric and categorical inputs (this requirement is for learning purposes). If it is appropriate, you may bin a metric variable into a categorical variable. 

You are not required to use any specific data source; nor are you prohibited from using any specific data source. You are allowed to add extra variables from other sources, but for each additional data source, the team will have to document and cite the source.


## Example of a Research Question 

Suppose that your team is interested in learning how the length of lanyard attached to a catapult affects customers’ satisfaction with the catapult. https://youtu.be/r9ENQ5j2zG4?t=15 

You work to develop a primary outcome: a measure of customer satisfaction reported on a 1-100 scale by customers. 

On Acme’s servers, you find data on lanyard length, maximum-rated weight for the catapult and sales region. However, when you are reasoning about the product, you also note that length of the catapult arm and size of the catapult wheels are also likely to affect customer satisfaction and are correlated with lanyard length. Because any model that does not include these confounding variables would yield estimates that conflate the importance of wheels and arms with the lanyard, you determine that the off-the-shelf data is not complete and that you need to encode the data yourself.

In the modeling phase of your project, your team proposes to build three models. One model estimates the relationship between catapult success and the modeling features that you identify should be in the model; a second estimates a similar model but against customer satisfaction. Finally, because you believe there may be a component of “learning how to use the product” the team estimates a third model that examines differences between lanyard-length based customer satisfaction for first-time purchasers vs. repeat purchasers. 


## A Group Assignment

**This is a group assignment.** Your live session instructor will coordinate the formation of groups. We would like to encourage teams to focus on using the lab as a way to learn how to work as a team of collaborating data scientists on shared code; how to clean and organize data; and, how to present work in a compelling way. As a result, we encourage teams to allow individuals to take risks and be supportive in the face of successes and failures. Create an opportunity for people who want to improve a particular skill to do so -- this might be project coordination, management of code through git, plotting, or any of the many aspects that you'll work on. *We hope that you can support and learn from one another through this team-based project.* 

# Deliverables 

| Deliverable Name       | Week Due | Grade Weight |
|------------------------|----------|--------------| 
| [Research Proposal]    | Week 12  | 10%          | 
| [Within-Team Review]   | Week 12  | 5%           | 
| [Final Presentation]   | Week 14  | 10%          | 
| [Final Report]         | Week 14  | 75%          | 
# Final Project Components {.tabset}

## Research Proposal

After a week of work, the project team will produce a one page research-proposal that defines the teams' research question, data sources and plan of action. 

The research question should be informed by an understanding of the datasets that are available, and the information that is available in those data sets. This means that the the team will need to have done at least preliminary work understand what data is available. A motivated team might form their research question, and begin to build a functioning data pipeline as an investment in ongoing project success. 

The research proposal is intended to provide a structure for the team to have early conversations; it will be graded credit/no credit for completeness (i.e. a reasonable effort by the team will receive full marks). Your instructor will read these proposals, and if any course corrections are necessary, will contact the team. 

**This proposal is due in week 12, and needs only one submission per team.**

## Within-Team Review

Being an effective, supportive team member is a crucial part of data science work. Your performance on this lab includes the role you play in supporting your teammates. This includes being responsive, creating an environment in which all members feel included, and above all treating each other with respect. In line with this perspective, we will ask each team member to write to two paragraphs to their instructor about the progress they have made individually, and the team has made as a whole toward completing their report. 

This self-assessment should: 

- Reflect on the strengths and weaknesses of the team and the team's process to this point in the project. 
   - Where your collaboration has worked well, how will you work to ensure that these successful practices continue to be employed? 
   - If there are places where collaboration has been challenging, what can the team do jointly to improve? 
- If there are any individual performances that deserve special recognition, please let your instructor know in this evaluation.
- If there are any individual performances that require special attention, please also let your instructor know in this evaluation. 

Instructors ill treat these reviews as confidential and will not take any action without first consulting you.

**This reflection is due in week 12, an requires one submission per person.** You will submit this through Gradescope, and like all parts of your educational record, this will be treated confidentially by the instructional team. 

## Final Presentation 

During the Unit 14 live session, each team will give a slide presentation of their work to their classmates -- i.e. collaborating data scientists. Your classmates they will need to be informed of the specific research question that you are addressing.  **The presentation should be structured as 10 minutes of presentation and 5 minutes of questions from our classmates.** We'd like to note that this is an *incredibly* limited amount of time to present. The materials that you present should reflect these serious constraints! 

1. There should be no more than two slides that set-up your research question and these slides should take no more than two minutes to present. On this slide, it is quite alright to state bluntly: "**Research Question**: Do subsidies on rental-income for craft beer breweries cause increases in brewing output and localized economic activity?" (2 minutes)
2. There should be at least one, and not more than two, slides that describe the variables that you're using in your models. These slides should cover the important features of the variables that you're using: how are they are measured, the unit of observation, plots of how these variables are distributed, and why this *particular* variable appropriate to use to answer your research question. (3 minutes) 
   - Do not present R code, discuss data wrangling, or normality - details like this are best left to the full analysis. 

3. There should then be several slides that provide what you've learned from your models. If you show model results, you need to provide your audience with enough time to read and engage with these models; not flash past them. Any model you show will take at least one minute to talk about. 

Finally, a few more general thoughts: 

- Practice your talk with a timer!
- If you divide your talk with your teammates, practice your section with a timer so that you do not spill over into your teammates' time.

## Final Report

Your final deliverable is a written statistical analysis documenting your findings. **Please limit your submission to 8000 words, excluding code cells and R output.**

The exact format of your report is flexible, but it should include the following elements.

### 1. An Introduction

Your introduction should present a research question and explain the concept that you're attempting to measure and how it will be operationalized. This section should pave the way for the body of the report, preparing the reader to understand why the models are constructed the way that they are. It is not enough to simply say, "We are looking for product features that enhance product success."  Your introduction must do work for you, focusing the reader on a specific measurement goal, making them care about it, and propelling the narrative forward. This is also a good time to put your work into context, discuss cross-cutting issues, and assess the overall appropriateness of the data.

### 2. A Model Building Process

You will next build a set of models to investigate your research question, documenting your decisions. Here are some things to keep in mind during your model building process:

1. *What do you want to measure*? Make sure you identify one, or a few, variables that will allow you to derive conclusions relevant to your research question, and include those variables in all model specifications. How are the variables that you will be modeling distributed? Provide enough context and information about your data for your audience to understand whatever model results you will eventually present. 
2. What [covariates](https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms) help you achieve your modeling goals? What covariates are problematic, either due to *collinearity*, or because they will absorb some of a causal effect you want to measure?
3. What *transformations*, if any, should you apply to each variable? These transformations might reveal linearities in the data, make our results relevant, or help us meet model assumptions.
4. Are your choices supported by exploratory data analysis (*EDA*)? You will likely start with some general EDA to *detect anomalies* (missing values, top-coded variables, etc.). From then on, your EDA should be interspersed with your model building. Use visual tools to *guide* your decisions. You can also leverage statistical *tests* to help assess whether variables, or groups of variables, are improving model fit.

At the same time, it is important to remember that you are not trying to create one perfect model. You will create several specifications, giving the reader a sense of how robust (or sensitive) your results are to modeling choices, and to show that you're not just cherry-picking the specification that leads to the largest effects.

At a minimum, you estimate at least three model specifications: 

The first model you include should include *only the key variables* you want to measure. These variables might be transformed, as determined by your EDA, but the model should include the absolute minimum number of covariates (usually zero or one covariate that is so crucial it would be unreasonable to omit it).

Additional models should each be defensible, and should continue to tell the story of how product features contribute to product success. This might mean including additional right-hand side features to remove omitted variable bias identified by your casual theory; or, instead, it might mean estimating a model that examines a related concept of success, or a model that investigates a heterogeneous effect. These models, and your modeling process should be defensible, incremental, and clearly explained at all points.

Your goal is to choose models that encircle the space of reasonable modeling choices, and to give an overall understanding of how these choices impact results.

### 3. A Regression Table

You should display all of your model specifications in a regression table, using a package like [`stargazer`](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf) to format your output. It should be easy for the reader to find the coefficients that represent key effects near the top of the regression table, and scan horizontally to see how they change from specification to specification. Make sure that you display the most appropriate standard errors in your table.

In your text, comment on both *statistical significance and practical significance*. You may want to include statistical tests besides the standard t-tests for regression coefficients. 

### 4. Limitations of your Model 

As a team, evaluate all of the CLM assumptions that must hold for your model. However, do not report an exhaustive examination all 5 CLM assumptions in the main report. Instead, bring forward only those assumptions that you or your reader might think pose significant problems for your analysis. For each problem that you identify, describe the statistical consequences. If you are able to identify any strategies to mitigate the consequences, explain these strategies. 

Note that you may need to change your model specifications in response to violations of the CLM. 

### 5. Discussion of Omitted Variables

If the team has taken up an explanatory (i.e. causal) question to evaluate, then identify what you think are the most important *omitted variables* that bias results you care about. For each variable you name, you should *reason about the direction of bias* caused by omitting this variable. If you can argue whether the bias is large or small, that is even better. State whether you have any variables available that may proxy (even imperfectly) for the omitted variable. Pay particular attention to whether each omitted variable bias is *towards zero or away from zero*. You will use this information to judge whether the effects you find are likely to be real, or whether they might be entirely an artifact of omitted variable bias.

### 6. Conclusion

Make sure that you end your report with a discussion that distills key insights from your estimates and addresses your research question. 

# Encouragement for the Project

This project touches on many of the skills that you have developed in the course. 

- When you are reasoning about the world and the way that it works, you are implicitly reasoning about *random variables*. Although you might not reason with specific functions (e.g. $f_{x} = x^2$) to describe these random variables, you are very likely to be reasoning about conditional expectations. In the example of craft-beer brewing from above, the question that the hypothetical team has proposed is one of how the expected value of beer production changes as a result of changes in policy inputs. 
- This class is not a class in pure theory! And so, theories you have about the world need to be informed by samples of data. These samples might be iid, or they might not be. The team will have to assess how this, and other possible violations of model assumptions shape what they learn. 
- Given a set of input variables, OLS regression produces an estimate of the BLP. But, how good of a predictor is this predictor? And, does the team have enough data to rely on large-sample theory, or does the team need to engage with the requirements of the smaller-sample? 
- Throughout, you will have to communicate both to a technical and non-technical audience. 

**Finally, have fun with this project.** You have worked hard this semester to build a foundation for reasoning about the world through statistical models. This project is a chance for you and a team of peers to work to apply this reasoning.




-------------
Odds and Ends

understanding of, intuition about, and data from the world to propose a question and generate an answer. Once you have a measurement goal, you will build a set of linear models that are tailored to that goal, and will present them to your readers in a manner that allows the reader to learn as much as possible. This might be a well formatted regression table or a series of tables and charts. 


 will be working as though you are product data scientists who have been asked, "What are the features of [this particular product or class of products] that make them more liked?" In taking on this project, you'll be dealing not only with many of the concepts from this course, but also concepts from 201, and 200 (if you took it). 


 
The principal difference between the work that you're doing in this lab, and what you might do as a product data scientist, is that you're not bound to any particular product, or even any particular industry. Your team could work in telecom, sports, fashion, entertainment, government services, climate, or anywhere else. 

The team's output from this project is to produce an analysis, report, and presentation of what makes a successful product. Bonus points if the team creates an example of a product that their model predicts would be the most successful. 
